spring:
  application:
    name: eureka
server:
  port: 8040
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8040/eureka/